name: Deploy to EC2

on:
  push:
    branches:
      - master
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production (master branch)
      if: github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/iatify-fe
          rm -rf ./vendor
          git fetch -a
          git stash --all
          git checkout master
          git stash --all
          git pull origin master

          # Install Composer dependencies
          composer install
          composer update

          # Install Node.js dependencies and build assets
          npm install
          npm run build
          
          rsync -av --delete --exclude='.git' /home/iatify-fe/ /var/www/html/iatify-prod
          chown -R www-data:www-data /var/www/html/iatify-prod
          find /var/www/html/iatify-prod -type d -exec chmod 755 {} \;
          find /var/www/html/iatify-prod -type f -exec chmod 644 {} \;
          cd /var/www/html/iatify-prod
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan config:cache
          sudo systemctl reload apache2

    - name: Deploy to Development (development branch)
      if: github.ref == 'refs/heads/development'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/iatify-fe
          rm -rf ./vendor
          git fetch -a
          git stash --all
          git checkout development
          git stash --all
          git pull origin development

          # Install Composer dependencies
          composer install
          composer update

          # Install Node.js dependencies and build assets
          npm install
          npm run build

          rsync -av --delete --exclude='.git' /home/iatify-fe/ /var/www/html/iatify-dev
          chown -R www-data:www-data /var/www/html/iatify-dev
          find /var/www/html/iatify-dev -type d -exec chmod 755 {} \;
          find /var/www/html/iatify-dev -type f -exec chmod 644 {} \;
          cd /var/www/html/iatify-dev
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan config:cache
          sudo systemctl reload apache2