name: Deploy Laravel Application on Contabo Server

on:
  push:
    branches:
      - master
      - development  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Laravel Application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Navigate to the project directory
          cd /home/iatify-fe
          
          # Pull the latest changes from the repository
          git pull
          
          # Sync the application files to the production directory
          rsync -av --delete --exclude='.git' /home/iatify-fe/ /var/www/html/iatify-prod
          
          # Set correct ownership and permissions
          chown -R www-data:www-data /var/www/html/iatify-prod
          find /var/www/html/iatify-prod -type d -exec chmod 755 {} \;
          find /var/www/html/iatify-prod -type f -exec chmod 644 {} \;

          # Clear cached configurations
          cd /var/www/html/iatify-prod
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan config:cache

          # Ensure correct Apache configuration and reload Apache
          rm /var/www/html/iatify-prod/bootstrap/cache/config.php
          sudo systemctl reload apache2

