name: Deploy Laravel Application

on:
  push:
    branches:
      - master
      - development # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your_server_ip >> ~/.ssh/known_hosts

    - name: Deploy Laravel Application
      run: |
        ssh root@your_server_ip "
          cd /home/iatify-fe &&
          git pull origin main &&
          composer install --no-interaction --prefer-dist --optimize-autoloader &&
          php artisan migrate --force &&
          php artisan config:cache &&
          php artisan route:cache &&
          php artisan view:cache &&
          rsync -av --exclude='.git' --exclude='node_modules' /home/iatify-fe/ /var/www/html/ &&
          chown -R www-data:www-data /var/www/html &&
          chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
        "
